import {defineImplementProblem} from '#problem-api';

export default defineImplementProblem({
	name: 'to-number',
	category: 'parsing',
	description: [
		'Parse a string to a number.',
		'Trim whitespace before parsing.',
		'Return null if the string is empty, blank, or contains any non-numeric characters.',
	],
	signature: 'function toNumber(s: string): number | null',
	tests: [
		"assert.strictEqual(toNumber('42'), 42);",
		"assert.strictEqual(toNumber('3.14'), 3.14);",
		"assert.strictEqual(toNumber('-7'), -7);",
		"assert.strictEqual(toNumber('-3.14'), -3.14);",
		"assert.strictEqual(toNumber('  42  '), 42);",
		"assert.strictEqual(toNumber('abc'), null);",
		"assert.strictEqual(toNumber(''), null);",
		"assert.strictEqual(toNumber('   '), null);",
		"assert.strictEqual(toNumber('12abc'), null);",
		"assert.strictEqual(toNumber('1.2.3'), null);",
		"assert.strictEqual(toNumber('-'), null);",
		"assert.strictEqual(toNumber('-.'), null);",
		"assert.strictEqual(toNumber('.'), null);",
		"assert.strictEqual(toNumber('Infinity'), null);",
		"assert.strictEqual(toNumber('-0'), 0);",
		"assert.strictEqual(toNumber('007'), 7);",
		"assert.strictEqual(toNumber('1+2'), null);",
		"assert.strictEqual(toNumber('1-2'), null);",
		"assert.strictEqual(toNumber('+-1'), null);",
		"assert.strictEqual(toNumber('--1'), null);",
		"assert.strictEqual(toNumber('++1'), null);",
		"assert.strictEqual(toNumber('1.'), null);",
	].join('\n'),
});
